version: '3.1'

services:

  back:
    build: ./epicash_api
    container_name: Back_NodeJS_TS
    depends_on:
      - db
    ports:
      - "4211"
    environment:
      PSQL_HOST: db


  db:
    image: postgres:14
    env_file: .env
    restart: always
    container_name: Base_de_donnees
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}